# Generated by Django 2.0 on 2018-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.TextField(max_length=100, unique=True)),
                ('pincode', models.TextField(max_length=50)),
            ],
        ),
    ]
