# Generated by Django 2.0 on 2018-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(max_length=50),
        ),
    ]
