# Generated by Django 2.0 on 2018-10-16 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0003_user_details_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='author',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
