# Generated by Django 2.0 on 2018-10-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0004_auto_20181016_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='author',
        ),
    ]
