# Generated by Django 2.0 on 2018-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0009_gov_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_fund',
            name='fund',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='pincode',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='user_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='aadhar_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(default=50),
        ),
    ]
