# Generated by Django 2.0 on 2018-10-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0010_auto_20181018_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_fund',
            name='fund',
            field=models.IntegerField(default=0),
        ),
    ]
