# Generated by Django 2.1.1 on 2018-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0012_track_users_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='city',
            field=models.TextField(default='asdf', max_length=10),
        ),
    ]
