# Generated by Django 2.0 on 2018-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0013_user_details_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_users',
            name='fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.TextField(default='asdf', max_length=15),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='city',
            field=models.TextField(default='asdf', max_length=15),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
