# Generated by Django 2.1.2 on 2018-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='list_todo',
            field=models.TextField(default='enter text'),
        ),
    ]
